FROM node:20-alpine AS build
WORKDIR /app
COPY packages/phishing-attempts-manage-service/. .
RUN npm install -g pnpm && pnpm install && pnpm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main"]
